### ISSUE TITLE
小米5 安装了这个apk但是好像不行啊 我本来都不玩了想试一下你这个结果开始玩了

### ISSUE THREAD

**Issue by zehuichen123** [Jacksgong/crash-pvp#2]

**Comment by Jacksgong** [comment]
😂 难道官方修复了？我好久没玩了，感觉这个和圈子有关，我最近身边没什么人玩，我就没有玩了。。

---

我看了下1月8日，确实Xposed发布了对Android 6、7、8的支持，话说你确定你的xposed其他模块都work吗？

**Comment by zehuichen123** [comment]
额 我只装了crashPvP试了一下 似乎不行 就是你readme里给的那个<a href="http://repo.xposed.info/module/cn.dreamtobe.xposed.crashpvp">链接</a>到Xposed的 然后我就直接进去了 狂玩了一晚上2333 我现在也不怎么玩了 不过室友老是玩 很烦 还看直播 唉～

**Comment by Jacksgong** [comment]
好吧。。。单独安装是不work的，需要先要安装Xposed框架的，这个模块是基于xposed的。

**Comment by zehuichen123** [comment]
嗯 好的 那推荐更进一下readme:需要xposed模块安装支持 不然像我这种不懂的就很懵逼了2333

**Comment by Jacksgong** [comment]
ok.
